steps:
  # Step 1: Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/meal-backend:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/meal-backend:$SHORT_SHA'
      - './backend'
    id: 'build-backend'

  # Step 2: Build Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/meal-frontend:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/meal-frontend:$SHORT_SHA'
      - './frontend'
    id: 'build-frontend'

  # Step 3: Push Backend Image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/meal-backend:latest'
    id: 'push-backend'

  # Step 4: Push Frontend Image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/meal-frontend:latest'
    id: 'push-frontend'

  # Step 5: Deploy Backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=.'
      - '--image=gcr.io/$PROJECT_ID/meal-backend:latest'
      - '--location=us-central1'
      - '--output=/workspace/deploy/'
    id: 'deploy-backend'
    
  # Step 6: Deploy Backend using gcloud
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'meal-backend'
      - '--image=gcr.io/$PROJECT_ID/meal-backend:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--set-env-vars=PORT=8080'
    id: 'deploy-backend-service'

  # Step 7: Get Backend URL and deploy frontend with it
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'meal-frontend'
      - '--image=gcr.io/$PROJECT_ID/meal-frontend:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=5173'
      - '--set-env-vars=VITE_BACKEND_URL=https://meal-backend-REGION-PROJECT_ID.run.app/'
    id: 'deploy-frontend-service'

# Store the images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/meal-backend:latest'
  - 'gcr.io/$PROJECT_ID/meal-frontend:latest'

# Build timeout
timeout: '1800s'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
